### ISSUE TITLE
re-staging after formatting

### ISSUE THREAD

**Issue by Faithfinder** [astral-sh/ruff-pre-commit#85]
It seems that `pre-commit` doesn't re-stage files that are changed, making auto-fixes and formatting in pre-commit, while not useless, a lot less ergonomic. Could this be handled on the hook's side?

**Comment by dhruvmanila** [comment]
I don't think that's possible because the hook only defines _how_ to run the command and does not control any part of `pre-commit` or `git`.

I'll close this issue as it's not actionable via `ruff-pre-commit`. Happy to re-open if there's new information on this.

**Comment by TizzySaurus** [comment]
> I don't think that's possible because the hook only defines _how_ to run the command and does not control any part of `pre-commit` or `git`.
> 
> I'll close this issue as it's not actionable via `ruff-pre-commit`. Happy to re-open if there's new information on this.

@dhruvmanila Having something as simple as `git add -u && !!` (re-stage all modified files that are already staged [i.e. the files changed by pre-commit hook] and re-run the one-before-last command [which will be the original `git commit`]) would allow a more seamless pre-commit integration, even if it required passing an extra flag to the ruff pre-commit hook in the `.pre-commit-config.yaml` and so wasn't enabled by default.

Having worked in the JS ecosystem, it feels very 'mundane' to have to manually do this when the pre-commit hook can quite easily handle this for the developer (as it does in the JS ecosystem).

**Comment by dhruvmanila** [comment]
> @dhruvmanila Having something as simple as `git add -u && !!` (re-stage all modified files that are already staged [i.e. the files changed by pre-commit hook] and re-run the one-before-last command [which will be the original `git commit`]) would allow a more seamless pre-commit integration, even if it required passing an extra flag to the ruff pre-commit hook in the `.pre-commit-config.yaml` and so wasn't enabled by default.

I'm not sure if I'd want to include additional commands (other than `ruff`) in the pre-commit hooks although other people on the team might have different opinion. There would be no way to _not_ do that if one wishes to do so. Everyone would by default be opted-in to this feature. There's also the fact that in CI the pre-commit check should fail but a hook re-stages the changes files and then the command passes, there's no way the PR author will know about that.

> Having worked in the JS ecosystem, it feels very 'mundane' to have to manually do this when the pre-commit hook can quite easily handle this for the developer (as it does in the JS ecosystem).

Can you please elaborate on what happens in the JS ecosystem? I'm not aware of it as I haven't worked that much in the ecosystem.

**Comment by TizzySaurus** [comment]
> There would be no way to not do that if one wishes to do so. Everyone would by default be opted-in to this feature. 

Is it not possible to add 'CLI' arguments to the pre-commit hook, like you have with the `ruff check` and `ruff format` commands? If it is, then you can have a `--restage-and-commit` flag, or akin, that's disabled by default but users can optionally enable.

> There's also the fact that in CI the pre-commit check should fail but a hook re-stages the changes files and then the command passes

The re-staging and committing will only happen if _all_ of the linting issues have been resolved automatically. If there's issues that can't be automatically resolved, then the hook errors and doesn't re-stage/commit.


> Can you please elaborate on what happens in the JS ecosystem? I'm not aware of it as I haven't worked that much in the ecosystem.

The JS ecosystem largely uses [husky](https://github.com/typicode/husky) for hook generation (equivalent of python's `pre-commit`), with [lint-staged](https://github.com/lint-staged/lint-staged) as the linter/formatter. When you go to commit a file, `husky` runs its pre-commit hook which is typically configured to trigger `lint-staged`.

The difference to Python is that when `lint-staged` runs, it applies any auto-fixable solutions _and_ if there's not any issues that it can't automatically fix it will re-stage & commit the result for the developer.

This means the JS workflow for solely auto-fixable linting issues is "commit a file", whereas the Python workflow (with Ruff) is "commit a file" -> "see that linting failed" -> "run linting manually" -> "see it's passing (because everything got auto-fixed)" -> "re-stage files" -> "commit again". The Python workflow is far more verbose, imo unnecessarily.

**Comment by codethief** [comment]
> I don't think that's possible because the hook only defines how to run the command and does not control any part of pre-commit or git.

What about something like
```
- id: ruff-format-and-stage-changes
  entry: sh -c 'ruff format --force-exclude "$@" && git add "$@"'
  …
```
?

(inspired by 
https://github.com/pre-commit/pre-commit/issues/747#issuecomment-386782080)

Add it stands, the current behavior of the `ruff-format` hook produces issues if you have carefully added changes to the staging area using `git add -p`. Then the following will happen upon `git commit`:

- `pre-commit` will stash the unstaged changes.
- `ruff format` will run only on the staged changes but the resulting re-formatted changes will be written to the working copy without staging them.
- `pre-commit` will unstash the unstaged changes on top of the now dirty working copy

As a result, I will have to carefully walk through `git add -p` again, while making sure I don't accidentally commit changes that I didn't want to include in the commit.
